# Generated by Django 5.1.7 on 2025-04-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='data_de_criacao',
            new_name='data',
        ),
    ]
