# Generated by Django 5.1.7 on 2025-04-14 15:39

import django.db.models.deletion
import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_data_de_criacao_postmodel_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidiaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(upload_to='posts_midia', validators=[posts.models.validar_midia])),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='posts.postmodel')),
            ],
        ),
    ]
