# Generated by Django 5.1.7 on 2025-04-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_midiapost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='midiapost',
            old_name='url',
            new_name='arquivo',
        ),
    ]
