# Generated by Django 5.1.1 on 2025-03-10 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnologias', '0001_initial'),
        ('users', '0002_user_bio_user_data_nascimento_user_endereco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('beginner', 'Iniciante'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado'), ('expert', 'Expert')], max_length=20)),
                ('tecnologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecnologias.tecnologiamodel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
