# Generated by Django 5.1.7 on 2025-04-12 13:46

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_name_alter_user_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='imagem',
            field=models.FileField(blank=True, default='user_pics/default.png', null=True, upload_to='user_pics', validators=[users.models.validar_imagem_usuario]),
        ),
    ]
