# Generated by Django 5.1.7 on 2025-04-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_instagram_user_linkedin_alter_user_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='endereco',
            new_name='localidade',
        ),
    ]
