# Generated by Django 5.1.7 on 2025-04-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_endereco_user_localidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='instagram',
            new_name='github',
        ),
    ]
