# Generated by Django 5.1.7 on 2025-04-12 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_instagram_user_github'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='portfolio',
        ),
    ]
