# Generated by Django 5.1.7 on 2025-04-21 18:49

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagem',
            field=models.FileField(blank=True, default='user_pics/default.png', null=True, upload_to=users.models.user_pic_upload_path, validators=[users.models.validar_imagem_usuario]),
        ),
    ]
