# Generated by Django 5.1.7 on 2025-05-06 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='localidade',
        ),
    ]
