# Generated by Django 5.1.1 on 2025-03-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnologias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologiamodel',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
