# Generated by Django 5.1.1 on 2025-03-10 23:25

import tecnologias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnologias', '0002_tecnologiamodel_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnologiamodel',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='tecnologias/', validators=[tecnologias.models.validar_tecnologia_imagem]),
        ),
    ]
